// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8gslj3jmhcLKwGyuV8BvtwpewbhRlGz8',
    appId: '1:646216687861:web:cabd9dbf656b36109ea5bc',
    messagingSenderId: '646216687861',
    projectId: 'login-register-ui-b651b',
    authDomain: 'login-register-ui-b651b.firebaseapp.com',
    storageBucket: 'login-register-ui-b651b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9rw1rpwjXqhqDmPLw6N4kloaJQrmOfxY',
    appId: '1:646216687861:android:056d5e34b617dfd29ea5bc',
    messagingSenderId: '646216687861',
    projectId: 'login-register-ui-b651b',
    storageBucket: 'login-register-ui-b651b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCExGsGk06em8gjANLCjwF-1Ixpv9Lwoes',
    appId: '1:646216687861:ios:65464981cbb563109ea5bc',
    messagingSenderId: '646216687861',
    projectId: 'login-register-ui-b651b',
    storageBucket: 'login-register-ui-b651b.appspot.com',
    iosClientId: '646216687861-ivk316bd0ufucqps2lau96i1qqera7n3.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegisterUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCExGsGk06em8gjANLCjwF-1Ixpv9Lwoes',
    appId: '1:646216687861:ios:65464981cbb563109ea5bc',
    messagingSenderId: '646216687861',
    projectId: 'login-register-ui-b651b',
    storageBucket: 'login-register-ui-b651b.appspot.com',
    iosClientId: '646216687861-ivk316bd0ufucqps2lau96i1qqera7n3.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegisterUi',
  );
}
